language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t sergesosnovski/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true sergesosnovski/react-test npm test

after_success:
  - docker build -t sergesosnovski/multi-client ./client
  - docker build -t sergesosnovski/multi-nginx ./nginx
  - docker build -t sergesosnovski/multi-server ./server
  - docker build -t sergesosnovski/multi-worker ./worker
  #Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #take those images and submit them to the docker hub
  - docker push sergesosnovski/multi-client
  - docker push sergesosnovski/multi-nginx
  - docker push sergesosnovski/multi-server
  - docker push sergesosnovski/multi-worker
